In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

df=pd.read_csv("/content/test2.csv")
df

   milk bread biscuit cornflakes bournvita  jam maggi  tea coffee cock sugar
0     t     t       t        NaN       NaN  NaN   NaN  NaN    NaN  NaN   NaN
1     t     t       t          t       NaN  NaN   NaN  NaN    NaN  NaN   NaN
2   NaN     t     NaN        NaN         t  NaN   NaN    t    NaN  NaN   NaN
3     t     t     NaN        NaN       NaN    t     t  NaN    NaN  NaN   NaN
4   NaN   NaN       t        NaN       NaN  NaN     t    t    NaN  NaN   NaN
5   NaN     t     NaN        NaN         t  NaN   NaN    t    NaN  NaN   NaN
6   NaN   NaN     NaN          t       NaN  NaN     t    t    NaN  NaN   NaN
7   NaN     t       t        NaN       NaN  NaN     t    t    NaN  NaN   NaN
8   NaN     t     NaN        NaN       NaN    t     t    t    NaN  NaN   NaN
9     t     t     NaN        NaN       NaN  NaN   NaN  NaN    NaN  NaN   NaN
10  NaN   NaN       t          t       NaN  NaN   NaN  NaN      t    t   NaN
11  NaN   NaN       t          t       NaN  NaN   NaN  NaN      t    t   NaN
12  NaN   NaN     NaN        NaN         t  NaN   NaN  NaN      t  NaN     t
13  NaN     t     NaN        NaN       NaN  NaN   NaN  NaN      t    t   NaN
14  NaN     t       t        NaN       NaN  NaN   NaN  NaN    NaN  NaN     t
15  NaN   NaN     NaN          t       NaN  NaN   NaN  NaN      t  NaN     t
16  NaN     t     NaN        NaN         t  NaN   NaN  NaN    NaN  NaN     t
17  NaN     t     NaN        NaN       NaN  NaN   NaN  NaN      t  NaN     t
18  NaN     t     NaN        NaN       NaN  NaN   NaN  NaN      t  NaN     t
19    t   NaN     NaN          t       NaN  NaN   NaN    t      t  NaN   NaN

In [ ]:
df_Binary= df.replace({'t': True, np.nan: False})
df_Binary.head()

,milk,bread,biscuit,cornflakes,bournvita,jam,maggi,tea,coffee,cock,sugar
0,True,True,True,False,False,False,False,False,False,False,False
1,True,True,True,True,False,False,False,False,False,False,False
2,False,True,False,False,True,False,False,True,False,False,False
3,True,True,False,False,False,True,True,False,False,False,False
4,False,False,True,False,False,False,True,True,False,False,False

In [ ]:
from mlxtend.frequent_patterns import apriori
frequent_itemsets=apriori(df_Binary,min_support=0.1,use_colnames=True)
frequent_itemsets

    support                             itemsets
0      0.25                               (milk)
1      0.65                              (bread)
2      0.35                            (biscuit)
3      0.30                         (cornflakes)
4      0.20                          (bournvita)
5      0.10                                (jam)
6      0.25                              (maggi)
7      0.35                                (tea)
8      0.40                             (coffee)
9      0.15                               (cock)
10     0.30                              (sugar)
11     0.20                        (bread, milk)
12     0.10                      (biscuit, milk)
13     0.10                   (cornflakes, milk)
14     0.20                     (bread, biscuit)
15     0.15                   (bournvita, bread)
16     0.10                         (bread, jam)
17     0.15                       (maggi, bread)
18     0.20                         (bread, tea)
19     0.15                      (coffee, bread)
20     0.20                       (sugar, bread)
21     0.15                (cornflakes, biscuit)
22     0.10                     (maggi, biscuit)
23     0.10                       (tea, biscuit)
24     0.10                    (coffee, biscuit)
25     0.10                      (cock, biscuit)
26     0.10                    (cornflakes, tea)
27     0.20                 (coffee, cornflakes)
28     0.10                   (cock, cornflakes)
29     0.10                     (bournvita, tea)
30     0.10                   (sugar, bournvita)
31     0.10                         (maggi, jam)
32     0.20                         (maggi, tea)
33     0.15                       (cock, coffee)
34     0.20                      (sugar, coffee)
35     0.10               (bread, biscuit, milk)
36     0.10              (bournvita, bread, tea)
37     0.10                  (maggi, bread, jam)
38     0.10                  (maggi, bread, tea)
39     0.10               (sugar, coffee, bread)
40     0.10        (coffee, biscuit, cornflakes)
41     0.10          (cock, cornflakes, biscuit)
42     0.10                (maggi, tea, biscuit)
43     0.10              (cock, coffee, biscuit)
44     0.10           (cock, coffee, cornflakes)
45     0.10  (cock, coffee, biscuit, cornflakes)

In [ ]:
from mlxtend.frequent_patterns import association_rules
confidence= association_rules(frequent_itemsets,metric="confidence",min_threshold=0.1,num_itemsets=2)
confidence

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(bread),(milk),0.65,0.25,0.2,0.307692,1.230769,1.0,0.0375,1.083333,0.535714,0.285714,0.076923,0.553846
1,(milk),(bread),0.25,0.65,0.2,0.800000,1.230769,1.0,0.0375,1.750000,0.250000,0.285714,0.428571,0.553846
2,(biscuit),(milk),0.35,0.25,0.1,0.285714,1.142857,1.0,0.0125,1.050000,0.192308,0.200000,0.047619,0.342857
3,(milk),(biscuit),0.25,0.35,0.1,0.400000,1.142857,1.0,0.0125,1.083333,0.166667,0.200000,0.076923,0.342857
4,(cornflakes),(milk),0.30,0.25,0.1,0.333333,1.333333,1.0,0.0250,1.125000,0.357143,0.222222,0.111111,0.366667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,"(cornflakes, biscuit)","(cock, coffee)",0.15,0.15,0.1,0.666667,4.444444,1.0,0.0775,2.550000,0.911765,0.500000,0.607843,0.666667
118,(cock),"(coffee, biscuit, cornflakes)",0.15,0.10,0.1,0.666667,6.666667,1.0,0.0850,2.700000,1.000000,0.666667,0.629630,0.833333
119,(coffee),"(cock, cornflakes, biscuit)",0.40,0.10,0.1,0.250000,2.500000,1.0,0.0600,1.200000,1.000000,0.250000,0.166667,0.625000
120,(biscuit),"(cock, coffee, cornflakes)",0.35,0.10,0.1,0.285714,2.857143,1.0,0.0650,1.260000,1.000000,0.285714,0.206349,0.642857
121,(cornflakes),"(cock, coffee, biscuit)",0.30,0.10,0.1,0.333333,3.333333,1.0,0.0700,1.350000,1.000000,0.333333,0.259259,0.666667

In [ ]:
confidence.columns

Index(['antecedents', 'consequents', 'antecedent support',
       'consequent support', 'support', 'confidence', 'lift',
       'representativity', 'leverage', 'conviction', 'zhangs_metric',
       'jaccard', 'certainty', 'kulczynski'],
      dtype='object')

In [ ]:
result=confidence[['antecedents', 'consequents','support', 'confidence', 'lift']]
result

,antecedents,consequents,support,confidence,lift
0,(bread),(milk),0.2,0.307692,1.230769
1,(milk),(bread),0.2,0.800000,1.230769
2,(biscuit),(milk),0.1,0.285714,1.142857
3,(milk),(biscuit),0.1,0.400000,1.142857
4,(cornflakes),(milk),0.1,0.333333,1.333333
...,...,...,...,...,...
117,"(cornflakes, biscuit)","(cock, coffee)",0.1,0.666667,4.444444
118,(cock),"(coffee, biscuit, cornflakes)",0.1,0.666667,6.666667
119,(coffee),"(cock, cornflakes, biscuit)",0.1,0.250000,2.500000
120,(biscuit),"(cock, coffee, cornflakes)",0.1,0.285714,2.857143
121,(cornflakes),"(cock, coffee, biscuit)",0.1,0.333333,3.333333

In [ ]:
result1=result[result.lift>1]
result1

,antecedents,consequents,support,confidence,lift
0,(bread),(milk),0.2,0.307692,1.230769
1,(milk),(bread),0.2,0.800000,1.230769
2,(biscuit),(milk),0.1,0.285714,1.142857
3,(milk),(biscuit),0.1,0.400000,1.142857
4,(cornflakes),(milk),0.1,0.333333,1.333333
...,...,...,...,...,...
117,"(cornflakes, biscuit)","(cock, coffee)",0.1,0.666667,4.444444
118,(cock),"(coffee, biscuit, cornflakes)",0.1,0.666667,6.666667
119,(coffee),"(cock, cornflakes, biscuit)",0.1,0.250000,2.500000
120,(biscuit),"(cock, coffee, cornflakes)",0.1,0.285714,2.857143
121,(cornflakes),"(cock, coffee, biscuit)",0.1,0.333333,3.333333

In [ ]:
result2=result[result.lift==1]
result2

Empty DataFrame
Columns: [antecedents, consequents, support, confidence, lift]
Index: []

In [ ]:
result1=result[result.lift<1]
result1

        antecedents      consequents  support  confidence      lift
6           (bread)        (biscuit)     0.20    0.307692  0.879121
7         (biscuit)          (bread)     0.20    0.571429  0.879121
12          (maggi)          (bread)     0.15    0.600000  0.923077
13          (bread)          (maggi)     0.15    0.230769  0.923077
14          (bread)            (tea)     0.20    0.307692  0.879121
15            (tea)          (bread)     0.20    0.571429  0.879121
16         (coffee)          (bread)     0.15    0.375000  0.576923
17          (bread)         (coffee)     0.15    0.230769  0.576923
24            (tea)        (biscuit)     0.10    0.285714  0.816327
25        (biscuit)            (tea)     0.10    0.285714  0.816327
26         (coffee)        (biscuit)     0.10    0.250000  0.714286
27        (biscuit)         (coffee)     0.10    0.285714  0.714286
30     (cornflakes)            (tea)     0.10    0.333333  0.952381
31            (tea)     (cornflakes)     0.10    0.285714  0.952381
67     (maggi, tea)          (bread)     0.10    0.500000  0.769231
70          (bread)     (maggi, tea)     0.10    0.153846  0.769231
72  (sugar, coffee)          (bread)     0.10    0.500000  0.769231
77          (bread)  (sugar, coffee)     0.10    0.153846  0.769231