In [48]:
import kagglehub
import pandas as pd
import numpy as np
import os

path = kagglehub.dataset_download("fredericobreno/play-tennis")
print("Path to dataset directory:", path)

csv_path = os.path.join(path, "play_tennis.csv")

# Load the data
data = pd.read_csv(csv_path)
data.head()

Using Colab cache for faster access to the 'play-tennis' dataset.
Path to dataset directory: /kaggle/input/play-tennis

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [49]:
data

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [50]:
# Problem 1
# outlook = sunny , Temp = Hot, Humidity = High, Wind = Weak
# play or not?

In [51]:
# solution
# P(Yes|Sunny,Hot,High,Weak) = P(Yes) * P(Sunny|Yes) * P(Hot|Yes) * P(High|Yes) * P(Weak|Yes)
# P(NO|Sunny,Hot,High,Weak) = P(NO) * P(Sunny|NO) * P(Hot|NO) * P(High|NO) * P(Weak|NO)

# Then We Will compare and decide using the maximum a posteriori rule

In [52]:
# Problem 2
# outlook = overcast , Temp = cold, Humidity = low, Wind = Weak
# play or not?

In [53]:
# solution
# P(Yes|Overcast, Cold, Low, Weak) = P(yes) * P(overcast|yes) * P(cold|Yes) * P(Low|Yes) * P(Weak|Yes)
# P(No|Overcast, Cold, Low, Weak) = P(No) * P(overcast|No) * P(cold|No) * P(Low|No) * P(Weak|No)
# Then We Will compare and decide using the maximum a posteriori rule

In [54]:
#Every algorithm works on a training step and a testing step.
#In the training step, the Naive Bayes self-organizes a look-up table in which it stores all the probabilities in a dictionary.

In [55]:
# P(Yes)
Prob_Of_Yes=data['play'].value_counts()['Yes']/len(data)
print(f"P(Yes): {Prob_Of_Yes}")

P(Yes): 0.6428571428571429

In [56]:
# P(no)
Prob_of_NO=data['play'].value_counts()['No'] / len(data)
print(f"P(No): {Prob_of_NO}")

P(No): 0.35714285714285715

In [57]:
# outlook
data['outlook'].unique()

array(['Sunny', 'Overcast', 'Rain'], dtype=object)

In [58]:
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [59]:
Prob_Overcast_Yes=data[data['play']=='Yes']['outlook'].value_counts()['Overcast']/data['play'].value_counts()['Yes']
Prob_Overcast_NO=data[data['play']=='No']['outlook'].value_counts().get('Overcast', 0)/data['play'].value_counts()['No']
print(Prob_Overcast_Yes,Prob_Overcast_NO,sep=" , ")

0.4444444444444444 , 0.0

In [60]:
Prob_Rain_Yes=data[data['play']=='Yes']['outlook'].value_counts()['Rain']/data['play'].value_counts()['Yes']
Prob_Rain_No=data[data['play']=='No']['outlook'].value_counts()['Rain']/data['play'].value_counts()['No']
print(f"P(Rain|Yes): {Prob_Rain_Yes} , P(Rain|No): {Prob_Rain_No} ")

P(Rain|Yes): 0.3333333333333333 , P(Rain|No): 0.4

In [61]:
Prob_Sunny_Yes=data[data['play']=='Yes']['outlook'].value_counts()['Sunny']/data['play'].value_counts()['Yes']
Prob_Sunny_No=data[data['play']=='No']['outlook'].value_counts()['Sunny']/data['play'].value_counts()['No']
print(f"P(Sunny|Yes):{Prob_Sunny_Yes}, P(Sunny|No): {Prob_Sunny_No}")

P(Sunny|Yes):0.2222222222222222, P(Sunny|No): 0.6

In [62]:
# Temperature
data['temp'].unique()

array(['Hot', 'Mild', 'Cool'], dtype=object)

In [63]:
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [64]:
Prob_Cool_Yes=data[data['play']=="Yes"]['temp'].value_counts()['Cool']/data['play'].value_counts()['Yes']
Prob_Cool_No=data[data['play']=="No"]['temp'].value_counts()['Cool']/data['play'].value_counts()['No']
print(f"P(Cool|Yes): {Prob_Cool_Yes}, P(Cool|No): {Prob_Cool_No}")

P(Cool|Yes): 0.3333333333333333, P(Cool|No): 0.2

In [65]:
Prob_Hot_Yes=data[data['play']=="Yes"]['temp'].value_counts()['Hot']/data['play'].value_counts()['Yes']
Prob_Hot_No=data[data['play']=="No"]['temp'].value_counts()['Hot']/data['play'].value_counts()['No']
print(f"P(Hot|Yes): {Prob_Hot_Yes}, P(Hot|No): {Prob_Hot_No}")

P(Hot|Yes): 0.2222222222222222, P(Hot|No): 0.4

In [66]:
Prob_Mild_Yes=data[data['play']=="Yes"]['temp'].value_counts()['Mild']/data['play'].value_counts()['Yes']
Prob_Mild_No=data[data['play']=="No"]['temp'].value_counts()['Mild']/data['play'].value_counts()['No']
print(f"P(Mild|Yes): {Prob_Mild_Yes}, P(Mild|No): {Prob_Mild_No}")

P(Mild|Yes): 0.4444444444444444, P(Mild|No): 0.4

Humidity

In [67]:
data['humidity'].unique()

array(['High', 'Normal'], dtype=object)

In [68]:
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [69]:
Prob_High_Yes=data[data['play']=="Yes"]['humidity'].value_counts()['High']/data['play'].value_counts()['Yes']
Prob_High_No=data[data['play']=="No"]['humidity'].value_counts()['High']/data['play'].value_counts()['Yes']
print(f"P(High|Yes): {Prob_High_Yes}, P(High|No): {Prob_High_No}")

P(High|Yes): 0.3333333333333333, P(High|No): 0.4444444444444444

In [83]:
Prob_Normal_Yes=data[data['play']=="Yes"]['humidity'].value_counts()['Normal']/data['play'].value_counts()['Yes']
Prob_Normal_No=data[data['play']=="No"]['humidity'].value_counts()['Normal']/data['play'].value_counts()['No']
print(f"P(Normal|Yes): {Prob_Normal_Yes}, P(Normal|No): {Prob_Normal_No}")

P(Normal|Yes): 0.6666666666666666, P(Normal|No): 0.2

In [71]:
 # Wind
data['wind'].unique()

array(['Weak', 'Strong'], dtype=object)

In [72]:
Prob_Weak_Yes=data[data['play']=="Yes"]['wind'].value_counts()['Weak']/data['play'].value_counts()['Yes']
Prob_Weak_No=data[data['play']=="No"]['wind'].value_counts()['Weak']/data['play'].value_counts()['No']
print(f"P(Weak|Yes): {Prob_Weak_Yes}, P(Weak|No): {Prob_Weak_No}")

P(Weak|Yes): 0.6666666666666666, P(Weak|No): 0.4

In [73]:
Prob_Strong_Yes=data[data['play']=="Yes"]['wind'].value_counts()['Strong']/data['play'].value_counts()['Yes']
Prob_Strong_No=data[data['play']=="No"]['wind'].value_counts()['Strong']/data['play'].value_counts()['No']
print(f"P(Strong|Yes): {Prob_Strong_Yes}, P(Strong|No): {Prob_Strong_No}")

P(Strong|Yes): 0.3333333333333333, P(Strong|No): 0.6

Solution

In [77]:
# Problem 1
# outlook = sunny , Temp = Hot, Humidity = High, Wind = Weak
Prob_Yes_Sunny_Hot_High_Weak=Prob_Of_Yes * Prob_Sunny_Yes * Prob_Hot_Yes * Prob_High_Yes * Prob_Weak_Yes
print(f"Probability of Yes, when outlook = sunny , Temp = Hot, Humidity = High, Wind = Weak")
print("OR")
print(f"P(Yes|Sunny,Hot,Humidity,Weak): {Prob_Yes_Sunny_Hot_High_Weak}")

Probability of Yes, when outlook = sunny , Temp = Hot, Humidity = High, Wind = Weak
OR
P(Yes|Sunny,Hot,Humidity,Weak): 0.007054673721340388

In [78]:
Prob_No_Sunny_Hot_High_Weak = Prob_of_NO * Prob_Sunny_No * Prob_Hot_No * Prob_High_No * Prob_Weak_No
print(f"Probability of No, when outlook = sunny , Temp = Hot, Humidity = High, Wind = Weak")
print("OR")
print(f"P(No|Sunny,Hot,Humidity,Weak): {Prob_No_Sunny_Hot_High_Weak}")

Probability of No, when outlook = sunny , Temp = Hot, Humidity = High, Wind = Weak
OR
P(No|Sunny,Hot,Humidity,Weak): 0.015238095238095238

In [80]:
if(Prob_Yes_Sunny_Hot_High_Weak>Prob_No_Sunny_Hot_High_Weak):
    print("Yes")
else:
    print("No")

No

In [82]:
# Problem 2
# outlook = overcast , Temp = cold, Humidity = Normal, Wind = Weak
# play or not?

Prob_Yes_Overcast_Cold_Normal_Weak=Prob_Of_Yes * Prob_Overcast_Yes * Prob_Cool_Yes * Prob_Normal_Yes * Prob_Weak_Yes
print(f"Probability of Yes, when outlook = overcast , Temp = cold, Humidity = Normal, Wind = Weak")
print("OR")
print(f"P(Yes|Overcast,Cold,Normal,Weak): {Prob_Yes_Overcast_Cold_Normal_Weak}")

Probability of Yes, when outlook = overcast , Temp = cold, Humidity = Normal, Wind = Weak
OR
P(Yes|Overcast,Cold,Normal,Weak): 0.012698412698412698

In [84]:
Prob_Yes_Overcast_Cold_Normal_Weak = Prob_of_NO * Prob_Overcast_NO * Prob_Cool_No * Prob_Normal_No * Prob_Weak_No
print(f"Probability of No, when outlook = overcast , Temp = cold, Humidity = Normal, Wind = Weak")
print("OR")
print(f"P(No|Overcast,Cold,Normal,Weak): {Prob_Yes_Overcast_Cold_Normal_Weak}")

Probability of No, when outlook = overcast , Temp = cold, Humidity = Normal, Wind = Weak
OR
P(No|Overcast,Cold,Normal,Weak): 0.0